services:
  db:
    image: postgres:14-alpine
    container_name: bookstore_db
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: bookstore_dev
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data ธซเธฒเธข

volumes:
  postgres_data:
